---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-demo
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |-
#
    global:
      resolve_timeout: 5m
    route:
      group_by:
      - cluster
      - alertname
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10s
#      receiver: 'email'
      routes:
      - receiver: email
        match:
          severity: warning
    receivers:
    - name: 'email'
      email_configs:
      - to: 'tdlam123@gmail.com'
        from: 'zkaratest@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'zkaratest@gmail.com'
        auth_identity: 'zkaratest@gmail.com'
        auth_password: 'Aa123456@'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
