---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongo-express
  namespace: default
  labels:
    team: devops
spec:
  endpoints:
    - port: http
      interval: 5s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: mongo-express
