---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: general
  namespace: monitoring
  labels:
    team: devops
spec:
  groups:
  - name: general
    rules:
    - alert: PeekTraffic
      annotations:
        message: '{{ $value }} http request per minute'
      expr: rate(http_requests_total[1m]) * 60 > 100
      for: 15s
      labels:
        severity: warning
